version: 0.2

env:
  git-credential-helper: yes

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cd ../projects/website && npm install && npm run build
      - cd ../../s3-website && npm install && npm run build && npm run cdk synth && npm run deploy
