version: '3'

services:
  aws_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: aws_node
    container_name: aws_node
    restart: unless-stopped
    environment:
      - ENV_PORT=ENV_PORT_PLACEHOLDER_
      - ENV_SRV=ENV_SRV_PLACEHOLDER_
      - ENV_MONGO_URI=mongodb://ENV_MONGO_HOST_PLACEHOLDER_:ENV_MONGO_PORT_PLACEHOLDER_/ENV_MONGO_DATABASE_PLACEHOLDER_
      - ENV_REDIS_URI=redis://ENV_REDIS_HOST_PLACEHOLDER_:ENV_REDIS_PORT_PLACEHOLDER_/0
      - ENV_ELASTIC_URI=http://ENV_ELASTIC_HOST_PLACEHOLDER_:ENV_ELASTIC_PORT_PLACEHOLDER_
    ports:
      - "ENV_PORT_PLACEHOLDER_:ENV_PORT_PLACEHOLDER_"
    networks:
      - app-network
    depends_on:
      - mongo
      - redis
      - elasticsearch

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - app-network  

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network    

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - 'discovery.type=single-node'
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge
